#!/usr/bin/env bash
# script that creates a file containing its PID

function del(){
    rm /var/run/myscript.pid
}

trap 'echo I hate the kill command;del' SIGTERM
trap "echo Y U no love me?!;del" SIGINT

echo $$ >> /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 1
done
