#!/usr/bin/env bash
# A manage_my_process Bash script
trap "echo I am alive!" SIGINT SIGTERM

echoecho $$ >> /var/run/myscript.pid
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
